# -*- coding: utf-8 -*-
"""wsgi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MZn_e2C8fneG3XJDAF9IsUxr2pwWYE9j
"""

from app import app, init_db

# Initialize database on application startup
init_db()

if __name__ == "__main__":
    app.run()